CREATE TABLE flysystem_files
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path        VARCHAR(255)                            NOT NULL,
    type        VARCHAR(4)                              NOT NULL,
    contents    BYTEA,
    size        INTEGER                                 NOT NULL DEFAULT 0,
    level       INTEGER                                 NOT NULL,
    mimetype    VARCHAR(127),
    visibility  VARCHAR(7)                              NOT NULL DEFAULT 'public',
    "timestamp" INTEGER                                 NOT NULL DEFAULT 0,
    CONSTRAINT flysystem_files_pk PRIMARY KEY (id),
    CONSTRAINT type_check CHECK (type = 'dir' OR type = 'file'),
    CONSTRAINT visibility_check CHECK (visibility = 'public' OR visibility = 'private'),
    CONSTRAINT path_unique UNIQUE (path)
);
