name: PHPStan

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP Action
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        ini-values: date.timezone=Europe/Budapest,memory_limit=-1,zend.assertions=1
        # Setup PHP version.
        php-version: ${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpstan
      run: composer run-script phpstan
